package com.pixel.create_ordnance.mechanics.scanning;

import com.pixel.create_ordnance.config.OrdnanceCommonConfig.ThrustType;

import net.minecraft.world.phys.Vec3;

/**
 * Immutable record containing all calculated physical properties of a
 * projectile.
 * Generated by the ProjectileAnalyzer based on a ScrapResult.
 */
public record ProjectileStats(
        // Mass & Stability
        double totalMass,
        Vec3 centerOfMass,
        double totalStability,
        Vec3 centerOfPressure,

        // Fuel Stats
        double totalFuel,
        double totalFuelConsumption,

        // Thrust Parameters
        ThrustType thrustType,
        double baseThrust,

        // Aerodynamics

        double maxNozzleTilt,
        double estimatedTerminalVelocity,

        // Lorentzian Resonance (Propulsive Efficiency)
        double optimalDensity,
        double densityBandwidth,

        // Unified Dual-Point Stats
        double massFront,
        double massBack,
        double volumeFront,
        double volumeBack,
        double areaFrontalFront,
        double areaFrontalBack,
        double areaLateralFront,
        double areaLateralBack,
        Vec3 centerFront,
        Vec3 centerBack,

        // Surface Area (Global)

        double totalLateralArea) {
}